// Generates Launchbay's app and tray icons procedurally (no image editor, no
// dependencies): anti-aliased signed-distance shapes rasterized to PNG, then
// packed into a multi-size ICO for the Windows build.
//
// The mark: a game box standing face-out, with the sticker-yellow favorite
// sticker on its corner. Run with `npm run icons`.

import { deflateSync } from 'node:zlib'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// ---------------------------------------------------------------- PNG / ICO

const CRC_TABLE = new Uint32Array(256).map((_, n) => {
  let c = n
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
  return c >>> 0
})

function crc32(buf) {
  let c = 0xffffffff
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

function chunk(type, data) {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(body))
  return Buffer.concat([len, body, crc])
}

// Provenance travels inside every PNG as a tEXt chunk (read it with any PNG inspector).
const PROVENANCE =
  'Procedurally generated by scripts/generate-icons.mjs: anti-aliased signed-distance shapes, no source image. ' +
  'A game box standing face-out with the sticker-yellow favorite sticker on its corner.'

function textChunk(keyword, text) {
  return chunk('tEXt', Buffer.concat([Buffer.from(keyword, 'latin1'), Buffer.from([0]), Buffer.from(text, 'latin1')]))
}

function encodePng(size, rgba) {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(size, 0)
  ihdr.writeUInt32BE(size, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 6 // RGBA
  const raw = Buffer.alloc((size * 4 + 1) * size)
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0 // filter: none
    rgba.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4)
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    textChunk('impeccable:prompt', PROVENANCE),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ])
}

function encodeIco(images) {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2) // icon
  header.writeUInt16LE(images.length, 4)
  const dir = Buffer.alloc(16 * images.length)
  let offset = 6 + dir.length
  images.forEach(({ size, png }, i) => {
    const e = i * 16
    dir[e] = size >= 256 ? 0 : size
    dir[e + 1] = size >= 256 ? 0 : size
    dir.writeUInt16LE(1, e + 4) // planes
    dir.writeUInt16LE(32, e + 6) // bpp
    dir.writeUInt32LE(png.length, e + 8)
    dir.writeUInt32LE(offset, e + 12)
    offset += png.length
  })
  return Buffer.concat([header, dir, ...images.map((i) => i.png)])
}

// ---------------------------------------------------------------- shapes (SDF, unit space 0..1)

const roundedBox = (px, py, cx, cy, hw, hh, r) => {
  const qx = Math.abs(px - cx) - hw + r
  const qy = Math.abs(py - cy) - hh + r
  return Math.hypot(Math.max(qx, 0), Math.max(qy, 0)) + Math.min(Math.max(qx, qy), 0) - r
}

const circle = (px, py, cx, cy, r) => Math.hypot(px - cx, py - cy) - r

// Five-point star (after Inigo Quilez's sdStar5).
function star5(px, py, cx, cy, r, rf) {
  const k1x = 0.809016994, k1y = -0.587785252
  const k2x = -k1x, k2y = k1y
  let x = Math.abs(px - cx)
  let y = -(py - cy)
  let d = 2 * Math.max(k1x * x + k1y * y, 0)
  x -= d * k1x
  y -= d * k1y
  d = 2 * Math.max(k2x * x + k2y * y, 0)
  x -= d * k2x
  y -= d * k2y
  x = Math.abs(x)
  y -= r
  const bax = rf * -k1y - 0, bay = rf * k1x - 1
  const h = Math.min(Math.max((x * bax + y * bay) / (bax * bax + bay * bay), 0), r)
  const dx = x - bax * h, dy = y - bay * h
  return Math.hypot(dx, dy) * Math.sign(dy * bax - dx * bay)
}

const hex = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)]

// Layers painted back to front: [sdf(px,py), rgb, alpha]
function appLayers() {
  const ground = hex('#131317')
  const shadow = hex('#000000')
  const back = hex('#3b3b42')
  const paper = hex('#ecebe6')
  const band = hex('#1d1d22')
  const yellow = hex('#ffcc33')
  const ink = hex('#1a1405')
  return [
    [(x, y) => roundedBox(x, y, 0.5, 0.5, 0.46, 0.46, 0.2), ground, 1],
    // a second box behind, peeking out on the left
    [(x, y) => roundedBox(x, y, 0.4, 0.53, 0.17, 0.25, 0.035), back, 1],
    // soft drop shadow under the front box
    [(x, y) => roundedBox(x, y, 0.56, 0.55, 0.19, 0.28, 0.05) - 0.02, shadow, 0.35],
    // the front box (2:3), face-out
    [(x, y) => roundedBox(x, y, 0.54, 0.52, 0.18, 0.27, 0.035), paper, 1],
    // its spec band: the "back of the box" block
    [(x, y) => roundedBox(x, y, 0.54, 0.66, 0.12, 0.028, 0.012), band, 0.9],
    [(x, y) => roundedBox(x, y, 0.5, 0.735, 0.08, 0.016, 0.008), band, 0.55],
    // the favorite sticker on the corner
    [(x, y) => circle(x, y, 0.7, 0.3, 0.125), yellow, 1],
    [(x, y) => star5(x, y, 0.7, 0.305, 0.072, 0.45), ink, 1]
  ]
}

function trayLayers() {
  const paper = hex('#ecebe6')
  const yellow = hex('#ffcc33')
  const ink = hex('#0d0d0f')
  return [
    // dark outline so the box still reads on a light taskbar
    [(x, y) => roundedBox(x, y, 0.44, 0.55, 0.27, 0.4, 0.06) - 0.06, ink, 1],
    [(x, y) => roundedBox(x, y, 0.44, 0.55, 0.27, 0.4, 0.06), paper, 1],
    [(x, y) => roundedBox(x, y, 0.44, 0.74, 0.17, 0.045, 0.02), ink, 0.85],
    [(x, y) => circle(x, y, 0.74, 0.27, 0.23), ink, 1], // cut ring so the sticker reads at 16px
    [(x, y) => circle(x, y, 0.74, 0.27, 0.19), yellow, 1]
  ]
}

function render(size, layers) {
  const out = Buffer.alloc(size * size * 4)
  const ss = 4 // 4x4 supersampling
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let r = 0, g = 0, b = 0, a = 0
      for (let sy = 0; sy < ss; sy++) {
        for (let sx = 0; sx < ss; sx++) {
          const x = (px + (sx + 0.5) / ss) / size
          const y = (py + (sy + 0.5) / ss) / size
          // composite layers (premultiplied "over")
          let cr = 0, cg = 0, cb = 0, ca = 0
          for (const [sdf, [lr, lg, lb], alpha] of layers) {
            if (sdf(x, y) > 0) continue
            const la = alpha
            cr = lr * la + cr * (1 - la)
            cg = lg * la + cg * (1 - la)
            cb = lb * la + cb * (1 - la)
            ca = la + ca * (1 - la)
          }
          r += cr
          g += cg
          b += cb
          a += ca
        }
      }
      const n = ss * ss
      const alpha = a / n
      const i = (py * size + px) * 4
      out[i] = alpha ? Math.round(r / n / alpha) : 0
      out[i + 1] = alpha ? Math.round(g / n / alpha) : 0
      out[i + 2] = alpha ? Math.round(b / n / alpha) : 0
      out[i + 3] = Math.round(alpha * 255)
    }
  }
  return out
}

function write(file, data) {
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, data)
  console.log(`wrote ${file.replace(root, '.')} (${data.length} bytes)`)
}

const app = appLayers()
const icoSizes = [16, 24, 32, 48, 64, 128, 256]
const icoImages = icoSizes.map((size) => ({ size, png: encodePng(size, render(size, app)) }))
write(join(root, 'build', 'icon.ico'), encodeIco(icoImages))
write(join(root, 'resources', 'icon.png'), encodePng(512, render(512, app)))
write(join(root, 'src', 'renderer', 'src', 'assets', 'mark.png'), encodePng(64, render(64, app)))

const tray = trayLayers()
write(join(root, 'resources', 'tray.png'), encodePng(16, render(16, tray)))
write(join(root, 'resources', 'tray@2x.png'), encodePng(32, render(32, tray)))
